### ISSUE TITLE
Windows drag'n'drop build?

### ISSUE THREAD

**Issue by Richard-L** [Focshole/whatsapp-media-exif-fixer#1]
Been desperately searching for a tool like this....!

Any chance you might build a windows executable or batch file where the user can drop multiple files on?

**Comment by Focshole** [comment]
Hello, yeah, i might do something like that. I have an unfinished project with wxPython, I might use it for producing a minimal UI with drag & drop.
Cannot provide you an ETA, but I will work on it in my free time (I will probably start next week, I'm very busy this one).

**Comment by Focshole** [comment]
I have started by adding a UI, it won't accept drag & drop at the moment but folders to open, probably tomorrow i'll make it Windows compatible too (and maybe allow also multiple files instead of directories)

**Comment by Focshole** [comment]
Drag & drop won't be available anywhere soon (it would require small backend changes but a lot of changes in the ui). 
Now a minimal UI is available, you can simply import your whatsapp pictures/videos folder from the menu. 
I have also provided an installer to ease the installation process. Reopen the issue if something else is needed.
